version: '2'
services:
  couchdb:
    image: couchdb
    volumes:
      - ./couchdb/local.ini:/usr/local/etc/couchdb/local.ini
  lucene:
    build: ./lucene
  linky:
    build: ./linky
    ports:
      - "8080:8080"
